### PR TITLE
Remove use of StandardAction

### LINKED ISSUE #78: StandardActionConvertible
`Use of undeclared type 'StandardActionConvertible'` in NavigationAction.swift

- Xcode: 8.3.3
- Swift 3.1
- iOS 10

### PR DESCRIPTION
**Pull request by hlineholm**
Fixes #78
Related to https://github.com/ReSwift/ReSwift/pull/270

### CODE REVIEW

**Comment by mjarvis** [comment]
We should see about moving this conformance into an extension in a separate file, and have a cocoapod subspec for recording conformance IE `pod 'ReSwift-Router/Recording'` or something

**Comment by hlineholm** [comment]
@mjarvis that sounds reasonable. How will we do it through Carthage? Might it be reasonable to move standard action back to ReSwift and add conformance in ReSwift-Recorder, ReSwift-Router and other future extensions and development tools built upon ReSwift?

**Comment by mjarvis** [comment]
@hlineholm I'm not certain how it would be done with carthage. Perhaps a separate framework would be needed, `ReSwift-RecordableRouter` or such, that provides the extensions, and has ReSwift & ReSwift-Router as dependencies?

I'm not inclined to add `StandardAction` back to ReSwift, as its not a core framework feature, but it does seem to make things confusing in regards to other frameworks providing `Recorder` capabilities...

**Comment by hlineholm** [comment]
@mjarvis FYI: I'm playing around with an action setup where I'm creating a "standard action" which u then specialise by setting the payload type. And I thought maybe this could be something we could use as a StandardAction in ReSwift. Not sure though how to make the dynamic payload type conform to CustomStringConvertible so that it can be serialized/deserialized.  This might be totally unuseful but I thought I'd put it out there for anyone to discuss with me. 

```
class Action<Payload>: ReSwift.Action, CustomStringConvertible {
    let payload: Payload
    init(_ payload: Payload) {
        self.payload = payload
    }
    var description: String {
        return "\(type)(\(payload))"
    }
    var type: String {
        return typeString(of: self)
    }
}
```

```
class CreateNode: Action<(path: ImagePath, node: Node)> {}
class CreateNodeSuccess: Action<Node> {}
class CreateNodeError: Action<Error> {}
class CreateSubnode: Action<(path: ImagePath, key: ParentKey)> {}
class CreateSubnodeSuccess: Action<Node> {}
class CreateSubnodeError: Action<Error> {}
```

**Comment by ranhsd** [comment]
Hi @hlineholm do you know when this pull request will be merged? 

Thanks,
Ran.

**Comment by ranhsd** [comment]
Hi @mjarvis Are you planning to merge it to master? 

Thanks.

**Comment by DivineDominion** [comment]
A propos serializing/deserializing the payload: what about Swift Codable conformance? Wouldn't that be feasible?

**Comment by hlineholm** [comment]
@mjarvis @DivineDominion I suggest we approve this PR and add an Issue for further discussions related to StandardAction. This is currently causing a build error.

**Comment by mjarvis** [comment]
I'm currently in the mindset that `ReSwift-Recorder` is going to be marked deprecated / unfinished, and as such, I'll merge this PR as-is, and we can shelf the re-addition of the `StandardAction` work to these actions in subspecs. If a user chooses to use the two of these they can easily extend the actions to conform or fork the repo themselves.

**Pull request merged**
