### PR TITLE
[Merge?] Swift 3.0.1 compatibility upgraded

### PR DESCRIPTION
**Pull request by DivineDominion**
Mostly Xcode project changes, but also fixing the test doubles to match protocol signatures so the tests don't crash.

I cannot seem to open the Recorder project, though. Anybody else with more luck?

### CODE REVIEW

**Comment by Ben-G** [comment]
@DivineDominion These changes look great, thanks! 🎉 

Is this actually still WIP? I can take care of the Recorder, but it seems the migration of the router is done?

**Comment by Ben-G** [comment]
@DivineDominion Actually I missed on thing. I just released `ReSwift 3.0.0`, could you change the `Cartfile` and `Podspec` to point to that release?

**Comment by juegas** [comment]
@Ben-G dependencies updated

**Comment by crobicha** [comment]
👍  Working for me with Xcode 8.1 and Swift 3.0.1

**Comment by Ben-G** [comment]
Thanks a lot @DivineDominion  🎉 Will cut a new release soon!

**Pull request merged**
