### PR TITLE
Rename Components of The Routable Protocol

### PR DESCRIPTION
**Pull request by hlineholm**
* Remove use of segment as it actually refers to route element
* Shorten names in order to increase readability without loosing unambiguity

### CODE REVIEW

**Comment by hlineholm-flir** [comment]
Should be squashed...

**Comment by mjarvis** [comment]
@hlineholm When making breaking changes like this (renaming, changing, or removing public members), we should try to build a habit of adding the new stuff, and then marking the old ones as deprecated (& pointing to the new items)

One can deprecate the old items here like this:
```swift
@available(*, deprecated, message: "Deprecated in favor of `RouteElement`") public typealias RouteElementIdentifier = RouteElement
```

This way we can push out a minor update and allow users to migrate before a major release with breaking changes.

**Comment by hlineholm-flir** [comment]
I'll add it!

**Comment by DivineDominion** [comment]
@hlineholm-flir Do you want to update this to the current master so we can merge this in?

**Comment by DivineDominion** [comment]
@hlineholm We've merged #116 with a similar intent, so this would be a great addition in the same vein. You could even skip the deprecation notices since there's breaking changes scheduled for v0.7 anyway. Could you rebase your branch or merge master into it?

**Comment by DivineDominion** [comment]
@hlineholm / @hlineholm-flir Are you still interested in updating the PR?

**Comment by hlineholm** [comment]
Yes @DivineDominion I'm interested in this PR getting merged to master. Are there any changes still required?

**Comment by hlineholm** [comment]
Yes @DivineDominion I am. Haven't had time to work on this so might be good if someone takes a look at the changes to see that I'm not missing anything. I've rebased it on latest master and in that process I discovered I'd missed some renaming in a test and in the README.md.

**Comment by DivineDominion** [comment]
Thanks! Looks good to me. I'll request another pair of eyes :)

**Comment by djtech42** [comment]
Looks good!

**Pull request merged**
