### PR TITLE
Update Deps

### PR DESCRIPTION
**Pull request by mzgnr**

### CODE REVIEW

**Comment by DivineDominion** [comment]
Thanks for the PR! While you're at it, could you also update the project settings to Xcode 10.2?

**Comment by mzgnr** [comment]
@DivineDominion I can take a look this weekend

**Comment by DivineDominion** [comment]
@mzgnr Did you find time to look into the changes?

**Comment by mzgnr** [comment]
@DivineDominion Its been really busy for two weeks. Ill take look at this weekend

**Comment by DivineDominion** [comment]
Contained in 0.7.1 already. Thanks for the PR so far, though!

**Pull request closed without merging**
