### PR TITLE
WIP Route via struct instead of string identifier

### PR DESCRIPTION
**Pull request by mjarvis**
**DO NOT MERGE** (much more work & discussions to be had)

This PR contains a pretty big change to the how routes are defined.
I found the string-typed identifiers un-swift-like, and the separation of route specific data from the route itself to be difficult to work with.

Instead of using a string identifier for a route segment, this implements a
`RouteSegment` struct thats used in its place.
`RouteSegment.instanceIdentifier` is used to uniquely identify intentional
duplicate segments. (IE if you have two of the same type of controllers in
your route)

Example usage:

```swift
struct TabBarControllerSegment {
   let instanceIdentifier: UUID = UUID()
}
let tabBar = TabBarControllerSegment()
store.dispatch(SetRouteAction(route: [tabBar]))
```

This lets us associate route-specific data right into the segment itself.

For example, specifying the user a UserViewController displays:

```swift
struct UserViewControllerSegment {
   let instanceIdentifier: UUID = UUID()
   let userIdentifier: Int
}
let user = UserViewControllerSegment(userIdentifier: 1)
store.dispatch(SetRouteAction(route: [tabBar, user]))
```

TODO:
- [ ] `SetRouteAction` to `StandardActionConvertible`
- [ ] Rebase this once #51 is merged to get rid of dupe commits
- [x] Changing route specific data for a given segment (& testing it doesn't do weird things)
- [ ] determine best practise for where segment instances are created (Maybe a static function on the controller?)
- [ ] determine best practise for associating instance identifier with controllers (UIViewController extension?)
- [ ] Update readme / documentation to reflect new usage

### CODE REVIEW

**Comment by mjarvis** [comment]
To note, due to this being based off of #51 , reviews / comments should look only at commit 		f1d6ad9

**Comment by mjarvis** [comment]
One of the flaws with this is holding onto route specific state for controllers that aren't currently visible, IE, maintaining state for tabs other than the selected tab. With this system, the segment object would be discarded, losing any state for that controller

**Comment by michalciurus** [comment]
Hello @mjarvis  👋 

I'm currently working on a router lib inspired by ReSwift-Router, but for [Katana](https://github.com/BendingSpoons/katana-swift).

I was also inspired by this PR to create a type-safe way to route, but I've taken another approach.

I'm using the *types* (metatype) of `Routable` concrete classes to identify the current destination.

Just letting you know, so maybe you'll take a look and maybe have some feedback ;)

 [KatanaRouter](https://github.com/michalciurus/KatanaRouter)

**Comment by mjarvis** [comment]
@michalciurus Thanks! I'll take a look when I've got some free time.

**Comment by Ben-G** [comment]
I'm assuming you're no longer pursuing this PR? I'm trying to clean up a little bit around here and will close this for now. Please feel free to re-open if this is still relevant!

**Pull request closed without merging**
